spring.application.name=teamtaskmanager
spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:6543/postgres?user=postgres.ilhahczmhbauqdsyiafv&password=Jeyasree@2528
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
supabase.jwt.secret=Vp98LRhLu4rQMelpRt3DtEQLHNvUMqns9BnMtm+lGk9bae+kBtJhkssIFUSyrbI/+FBvlrdAo9odF7m2XqUxMw==
supabase.url=https://ilhahczmhbauqdsyiafv.supabase.co
supabase.service.key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlsaGFoY3ptaGJhdXFkc3lpYWZ2Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3NTgyMTQ4MiwiZXhwIjoyMDkxMzk3NDgyfQ.RqAJtBg3JMdXZSWgu0_SBEMGREZ_gS-KwKKXX0IQXPg
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://ilhahczmhbauqdsyiafv.supabase.co/auth/v1
